" Vim syntax file for Piton. Generated by `piton grammar`.
if exists("b:current_syntax")
  finish
endif

syntax keyword pitonKeyword anchor abstract extends as export from import use
syntax keyword pitonSelf this self super
syntax keyword pitonBoolean true false null
syntax keyword pitonType string number boolean null list dictionary anchor any simple complex contained
syntax keyword pitonFrameworkKeyword agent belay-adapter belay-agent-adapter belay-config command instruction self-instruction skill
highlight default link pitonFrameworkKeyword Function

" A comment starts a line or follows whitespace, so URLs survive.
syntax match pitonComment "\%(^\|\s\)//.*$" contains=@Spell

" `key:` and `key:: type:`
syntax match pitonKey "^\s*[A-Za-z_][A-Za-z0-9_-]*\ze\s*\%(::\|:\)\%(\s\|$\)"
syntax match pitonTypeOp "::" nextgroup=pitonTypeName skipwhite
syntax match pitonTypeName "\<\%(extends\s\+\)\?[A-Za-z_][A-Za-z0-9_-]*\%(\[\]\)*" contained contains=pitonType

syntax match pitonAnchorName "\%(\<anchor\s\+\)\@<=[A-Za-z_][A-Za-z0-9_-]*"
syntax match pitonBullet "^\s*-\ze\s"
syntax match pitonSpread "^\s*++\?\ze\s"
syntax match pitonPath "\%(\<\%(from\|use\)\s\+\)\@<=\S\+"

syntax match pitonNumber "\<\d[0-9_]*\%(\.\d[0-9_]*\)\?\>"
syntax region pitonString start=+"+ skip=+\\.+ end=+"+ contains=pitonEscape
syntax match pitonEscape "\\." contained
syntax region pitonInterp matchgroup=pitonSigil start="[^ \t{}[\](),\"]*{" end="}" contains=pitonSelf,pitonBoolean,pitonNumber,pitonString,pitonOperator
syntax match pitonOperator "\%(\s\|^\|(\|\[\|,\)\@<=\%(++\|&&\|||\|==\|!=\|>=\|<=\|[-+*/%<>?:]\)\%(\s\|$\|)\|\]\|,\)\@="

" A fenced code block is kept as written, so nothing inside it is Piton. It is
" defined last so that it wins over every rule above, and it closes only at a
" run of the same fence character at least as long as the one that opened it.
syntax region pitonFence matchgroup=pitonFenceMark start="^\s\+\z(```\+\|\~\~\~\+\)[^`]*$" end="^\s*\z1\%(`\|\~\)*\s*$" keepend

highlight default link pitonKeyword Keyword
highlight default link pitonSelf Identifier
highlight default link pitonBoolean Boolean
highlight default link pitonType Type
highlight default link pitonTypeName Type
highlight default link pitonTypeOp Operator
highlight default link pitonComment Comment
highlight default link pitonKey Identifier
highlight default link pitonAnchorName Structure
highlight default link pitonBullet Delimiter
highlight default link pitonSpread Operator
highlight default link pitonPath String
highlight default link pitonNumber Number
highlight default link pitonString String
highlight default link pitonEscape SpecialChar
highlight default link pitonSigil PreProc
highlight default link pitonOperator Operator
highlight default link pitonFence String
highlight default link pitonFenceMark Delimiter

let b:current_syntax = "piton"
