// Generated by `piton grammar`. Edit crates/piton-grammar instead.

use zed_extension_api::{self as zed, settings::LspSettings, Command, LanguageServerId, Result};

/// The binary that serves Piton, and the subcommand that starts the server.
const BINARY: &str = "piton";
const SUBCOMMAND: &str = "lsp";

struct PitonExtension;

impl zed::Extension for PitonExtension {
    fn new() -> Self {
        PitonExtension
    }

    fn language_server_command(
        &mut self,
        language_server_id: &LanguageServerId,
        worktree: &zed::Worktree,
    ) -> Result<Command> {
        // An explicit `lsp.piton.binary` in the user's settings wins.
        let settings = LspSettings::for_worktree(language_server_id.as_ref(), worktree)
            .ok()
            .and_then(|settings| settings.binary);
        if let Some(binary) = settings {
            if let Some(path) = binary.path {
                return Ok(Command {
                    command: path,
                    args: binary.arguments.unwrap_or_else(|| vec![SUBCOMMAND.to_string()]),
                    env: worktree.shell_env(),
                });
            }
        }

        let path = worktree.which(BINARY).ok_or_else(|| {
            format!(
                "could not find `{BINARY}` on $PATH. Build it with `cargo xtask install`, or set                  lsp.piton.binary.path in your Zed settings."
            )
        })?;

        Ok(Command {
            command: path,
            args: vec![SUBCOMMAND.to_string()],
            env: worktree.shell_env(),
        })
    }
}

zed::register_extension!(PitonExtension);
