/**
 * An Astro integration for Piton.
 *
 * Astro builds on Vite, so this adds the Vite plugin to Astro's own Vite
 * configuration and gets out of the way. Everything the plugin does -- named
 * exports, hot reload, dependency tracking, virtual modules, renderers -- follows
 * from that, and works the same in an Astro project as in a bare Vite one.
 *
 * The type declarations for `.pi` imports are added too, since Astro projects
 * are type-checked by default and `import spec from './app.pi'` is otherwise
 * an error in the editor.
 */

import piton, { type PitonPluginOptions } from 'vite-plugin-piton';

export interface AstroPitonOptions extends PitonPluginOptions {}

/**
 * The same declarations as `vite-plugin-piton/client`.
 *
 * Each export of a Piton file is a named export and the default export is the
 * whole file. Which names a file exports depends on the file, so these are
 * shorthand declarations: every import from a `.pi` module is typed `any`.
 */
const TYPES = [
  '// Generated by astro-piton: `.pi` imports.',
  "declare module '*.pi';",
  "declare module 'virtual:piton/*';",
  '',
].join('\n');

/** Piton support for an Astro project. */
export default function astroPiton(options: AstroPitonOptions = {}) {
  return {
    name: 'astro-piton',
    hooks: {
      'astro:config:setup': ({
        updateConfig,
      }: {
        updateConfig: (config: Record<string, unknown>) => void;
      }) => {
        updateConfig({ vite: { plugins: [piton(options)] } });
      },

      'astro:config:done': ({
        injectTypes,
      }: {
        injectTypes?: (types: { filename: string; content: string }) => void;
      }) => {
        // Older Astro versions have no `injectTypes`; the plugin still works,
        // the editor just will not know about `.pi` imports.
        injectTypes?.({ filename: 'piton.d.ts', content: TYPES });
      },
    },
  };
}

export {
  json,
  yaml,
  markdown,
  render,
  renderFile,
  compileFile,
  type Renderer,
} from 'vite-plugin-piton';
