//! Editors that want their own native syntax file: Vim, Emacs, Sublime Text,
//! Kate, and Helix.

use crate::{GeneratedFile, GrammarSource, Vocabulary};

pub fn files(vocabulary: &Vocabulary, source: &GrammarSource) -> Vec<GeneratedFile> {
    vec![
        GeneratedFile::new("vim/syntax/piton.vim", vim_syntax(vocabulary)),
        GeneratedFile::new("vim/ftdetect/piton.vim", vim_ftdetect()),
        GeneratedFile::new("vim/ftplugin/piton.vim", vim_ftplugin()),
        GeneratedFile::new("vim/lua/piton/init.lua", neovim_lua(source)),
        GeneratedFile::new("vim/README.md", vim_readme()),
        GeneratedFile::new("emacs/piton-mode.el", emacs_mode(vocabulary)),
        GeneratedFile::new("emacs/README.md", emacs_readme()),
        GeneratedFile::new("sublime/Piton.sublime-syntax", sublime_syntax(vocabulary)),
        GeneratedFile::new("sublime/LSP-piton.sublime-settings", sublime_lsp()),
        GeneratedFile::new("sublime/README.md", sublime_readme()),
        GeneratedFile::new("helix/languages.toml", helix_languages(source)),
        GeneratedFile::new("helix/README.md", helix_readme()),
        GeneratedFile::new("kate/piton.xml", kate_syntax(vocabulary)),
        GeneratedFile::new("kate/README.md", kate_readme()),
    ]
}

// ---- Vim ------------------------------------------------------------------

fn vim_syntax(vocabulary: &Vocabulary) -> String {
    let declaration = vocabulary.declaration.join(" ");
    let self_words = vocabulary.self_words.join(" ");
    let literals = vocabulary.literals.join(" ");
    let types = vocabulary.types.join(" ");
    let framework = vocabulary.framework.join(" ");
    let framework_rule = if framework.is_empty() {
        String::new()
    } else {
        format!(
            "syntax keyword pitonFrameworkKeyword {framework}\nhighlight default link pitonFrameworkKeyword Function\n"
        )
    };
    format!(
        r#"" Vim syntax file for Piton. Generated by `piton grammar`.
if exists("b:current_syntax")
  finish
endif

syntax keyword pitonKeyword {declaration}
syntax keyword pitonSelf {self_words}
syntax keyword pitonBoolean {literals}
syntax keyword pitonType {types} contained
{framework_rule}
" A comment starts a line or follows whitespace, so URLs survive.
syntax match pitonComment "\%(^\|\s\)//.*$" contains=@Spell

" `key:` and `key:: type:`
syntax match pitonKey "^\s*[A-Za-z_][A-Za-z0-9_-]*\ze\s*\%(::\|:\)\%(\s\|$\)"
syntax match pitonTypeOp "::" nextgroup=pitonTypeName skipwhite
syntax match pitonTypeName "\<\%(extends\s\+\)\?[A-Za-z_][A-Za-z0-9_-]*\%(\[\]\)*" contained contains=pitonType

syntax match pitonAnchorName "\%(\<anchor\s\+\)\@<=[A-Za-z_][A-Za-z0-9_-]*"
syntax match pitonBullet "^\s*-\ze\s"
syntax match pitonSpread "^\s*++\?\ze\s"
syntax match pitonPath "\%(\<\%(from\|use\)\s\+\)\@<=\S\+"

syntax match pitonNumber "\<\d[0-9_]*\%(\.\d[0-9_]*\)\?\>"
syntax region pitonString start=+"+ skip=+\\.+ end=+"+ contains=pitonEscape
syntax match pitonEscape "\\." contained
syntax region pitonInterp matchgroup=pitonSigil start="[^ \t{{}}[\](),\"]*{{" end="}}" contains=pitonSelf,pitonBoolean,pitonNumber,pitonString,pitonOperator
syntax match pitonOperator "\%(\s\|^\|(\|\[\|,\)\@<=\%(++\|&&\|||\|==\|!=\|>=\|<=\|[-+*/%<>?:]\)\%(\s\|$\|)\|\]\|,\)\@="

highlight default link pitonKeyword Keyword
highlight default link pitonSelf Identifier
highlight default link pitonBoolean Boolean
highlight default link pitonType Type
highlight default link pitonTypeName Type
highlight default link pitonTypeOp Operator
highlight default link pitonComment Comment
highlight default link pitonKey Identifier
highlight default link pitonAnchorName Structure
highlight default link pitonBullet Delimiter
highlight default link pitonSpread Operator
highlight default link pitonPath String
highlight default link pitonNumber Number
highlight default link pitonString String
highlight default link pitonEscape SpecialChar
highlight default link pitonSigil PreProc
highlight default link pitonOperator Operator

let b:current_syntax = "piton"
"#
    )
}

fn vim_ftdetect() -> String {
    r#"" Generated by `piton grammar`.
autocmd BufRead,BufNewFile *.pi setfiletype piton
autocmd BufRead,BufNewFile piton.config.pi setfiletype piton
"#
    .to_string()
}

fn vim_ftplugin() -> String {
    r#"" Generated by `piton grammar`.
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

setlocal expandtab
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal tabstop=4
setlocal commentstring=//\ %s
setlocal comments=:https://,:// 
setlocal foldmethod=indent
setlocal formatprg=piton\ format\ -
"#
    .to_string()
}

fn neovim_lua(source: &GrammarSource) -> String {
    format!(
        r#"-- Generated by `piton grammar`.
--
-- Registers Piton with Neovim's built-in LSP client and, when the Tree-sitter
-- grammar is installed, with nvim-treesitter.

local M = {{}}

--- @param opts table|nil  Passed through to vim.lsp.start.
function M.setup(opts)
  opts = opts or {{}}
  vim.filetype.add({{ extension = {{ pi = 'piton' }} }})

  local group = vim.api.nvim_create_augroup('PitonLsp', {{ clear = true }})
  vim.api.nvim_create_autocmd('FileType', {{
    group = group,
    pattern = 'piton',
    callback = function(args)
      vim.lsp.start(vim.tbl_extend('force', {{
        name = 'piton',
        cmd = opts.cmd or {{ 'piton', 'lsp' }},
        root_dir = vim.fs.dirname(vim.fs.find({{ 'piton.config.pi', '.git' }}, {{
          upward = true,
          path = vim.api.nvim_buf_get_name(args.buf),
        }})[1]),
      }}, opts))
    end,
  }})

  local ok, parsers = pcall(require, 'nvim-treesitter.parsers')
  if ok then
    parsers.get_parser_configs().piton = {{
      install_info = {{
        url = opts.grammar_url or '{remote}',
        revision = opts.grammar_revision or '{rev}',
        files = {{ 'src/parser.c' }},
      }},
      filetype = 'piton',
    }}
  end
end

return M
"#,
        remote = source.repository,
        rev = source.rev
    )
}

fn vim_readme() -> String {
    r#"# Piton for Vim and Neovim

Generated by `piton grammar`.

## Vim

Copy `syntax/`, `ftdetect/`, and `ftplugin/` into `~/.vim`, or point a plugin
manager at this directory:

```vim
Plug 'piton-lang/piton', { 'rtp': 'editors/vim' }
```

## Neovim

Add this directory to `runtimepath` and call the setup function:

```lua
require('piton').setup()
```

That registers the `piton` filetype and starts `piton lsp` for it. Pass
`cmd = { '/path/to/piton', 'lsp' }` if the binary is not on `$PATH`.
"#
    .to_string()
}

// ---- Emacs -----------------------------------------------------------------

fn emacs_mode(vocabulary: &Vocabulary) -> String {
    let quote = |words: &[String]| {
        words.iter().map(|word| format!("\"{word}\"")).collect::<Vec<_>>().join(" ")
    };
    format!(
        r#";;; piton-mode.el --- Major mode for the Piton language -*- lexical-binding: t; -*-

;; Generated by `piton grammar'.  Edit crates/piton-grammar instead.

;; Version: 0.1.0
;; Package-Requires: ((emacs "27.1"))
;; Keywords: languages

;;; Commentary:

;; Font locking, indentation, and language-server registration for Piton
;; (`.pi') files.  Piton is whitespace-structured, so indentation is handled by
;; cycling through plausible levels rather than by guessing one.

;;; Code:

(defgroup piton nil
  "Support for the Piton language."
  :group 'languages
  :prefix "piton-")

(defcustom piton-indent-offset 4
  "Number of spaces per indentation level.  Piton's canonical style is four."
  :type 'integer
  :group 'piton)

(defcustom piton-command "piton"
  "Path to the piton executable."
  :type 'string
  :group 'piton)

(defconst piton--keywords '({declaration}))
(defconst piton--self-words '({self_words}))
(defconst piton--constants '({literals}))
(defconst piton--types '({types}))
(defconst piton--framework-keywords '({framework}))

(defconst piton-font-lock-keywords
  (list
   ;; A comment starts a line or follows whitespace, so URLs survive.
   '("\\(?:^\\|[[:space:]]\\)\\(//.*\\)$" 1 font-lock-comment-face)
   `(,(concat "\\_<" (regexp-opt piton--keywords) "\\_>") . font-lock-keyword-face)
   `(,(concat "\\_<" (regexp-opt piton--self-words) "\\_>") . font-lock-builtin-face)
   `(,(concat "\\_<" (regexp-opt piton--constants) "\\_>") . font-lock-constant-face)
   (when piton--framework-keywords
     `(,(concat "^[[:space:]]*" (regexp-opt piton--framework-keywords) "\\_>")
       . font-lock-preprocessor-face))
   '("^[[:space:]]*\\(?:export[[:space:]]+\\)?\\(?:abstract[[:space:]]+\\)?anchor[[:space:]]+\\([A-Za-z_][A-Za-z0-9_-]*\\)"
     1 font-lock-type-face)
   '("^[[:space:]]*\\([A-Za-z_][A-Za-z0-9_-]*\\)[[:space:]]*\\(?:::\\|:\\)\\(?:[[:space:]]\\|$\\)"
     1 font-lock-variable-name-face)
   `(,(concat "::[[:space:]]*\\(?:extends[[:space:]]+\\)?\\("
              (regexp-opt piton--types) "\\|[A-Za-z_][A-Za-z0-9_-]*\\)")
     1 font-lock-type-face)
   '("[^ \t{{}}\\[\\](),\"]*{{[^}}]*}}" 0 font-lock-preprocessor-face keep)
   '("\\_<[0-9][0-9_]*\\(?:\\.[0-9][0-9_]*\\)?\\_>" . font-lock-constant-face)
   '("^[[:space:]]*\\(-\\)[[:space:]]" 1 font-lock-negation-char-face)
   '("^[[:space:]]*\\(\\+\\+?\\)[[:space:]]" 1 font-lock-warning-face))
  "Font lock rules for `piton-mode'.")

(defvar piton-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?/ ". 12" table)
    (modify-syntax-entry ?\n ">" table)
    (modify-syntax-entry ?\" "\"" table)
    (modify-syntax-entry ?- "_" table)
    (modify-syntax-entry ?_ "_" table)
    table)
  "Syntax table for `piton-mode'.")

(defun piton--previous-indent ()
  "Indentation of the closest preceding non-blank line."
  (save-excursion
    (forward-line -1)
    (while (and (not (bobp)) (looking-at "^[[:space:]]*$"))
      (forward-line -1))
    (cons (current-indentation)
          (save-excursion (end-of-line) (looking-back ":[[:space:]]*" (line-beginning-position))))))

(defun piton-indent-line ()
  "Indent the current line, cycling through plausible levels on repeat."
  (interactive)
  (let* ((previous (piton--previous-indent))
         (base (car previous))
         (opens (cdr previous))
         (maximum (+ base (if opens piton-indent-offset 0)))
         (current (current-indentation)))
    (indent-line-to
     (if (and (eq last-command 'indent-for-tab-command) (> current 0))
         (max 0 (- current piton-indent-offset))
       maximum))))

(defun piton-format-buffer ()
  "Format the current buffer with `piton format'."
  (interactive)
  (let ((point (point)))
    (call-process-region (point-min) (point-max) piton-command t t nil "format" "-")
    (goto-char (min point (point-max)))))

;;;###autoload
(define-derived-mode piton-mode prog-mode "Piton"
  "Major mode for editing Piton source."
  :syntax-table piton-mode-syntax-table
  (setq-local font-lock-defaults '(piton-font-lock-keywords nil nil nil nil))
  (setq-local comment-start "// ")
  (setq-local comment-end "")
  (setq-local comment-start-skip "//+[[:space:]]*")
  (setq-local indent-line-function #'piton-indent-line)
  (setq-local indent-tabs-mode nil)
  (setq-local tab-width piton-indent-offset)
  (setq-local require-final-newline t))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.pi\\'" . piton-mode))

;; Language server registration for both popular clients.
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               `(piton-mode . (,piton-command "lsp"))))

(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration '(piton-mode . "piton"))
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection (list piton-command "lsp"))
                    :activation-fn (lsp-activate-on "piton")
                    :server-id 'piton)))

(provide 'piton-mode)
;;; piton-mode.el ends here
"#,
        declaration = quote(&vocabulary.declaration),
        self_words = quote(&vocabulary.self_words),
        literals = quote(&vocabulary.literals),
        types = quote(&vocabulary.types),
        framework = quote(&vocabulary.framework),
    )
}

fn emacs_readme() -> String {
    r#"# Piton for Emacs

Generated by `piton grammar`.

```elisp
(add-to-list 'load-path "/path/to/piton/editors/emacs")
(require 'piton-mode)
```

`piton-mode` registers itself with both `eglot` and `lsp-mode`; either will
start `piton lsp` when you open a `.pi` file. `M-x piton-format-buffer` runs the
canonical formatter.
"#
    .to_string()
}

// ---- Sublime Text -----------------------------------------------------------

fn sublime_syntax(vocabulary: &Vocabulary) -> String {
    let declaration = Vocabulary::alternation(&vocabulary.declaration);
    let self_words = Vocabulary::alternation(&vocabulary.self_words);
    let literals = Vocabulary::alternation(&vocabulary.literals);
    let types = Vocabulary::alternation(&vocabulary.types);
    format!(
        r#"%YAML 1.2
---
# Generated by `piton grammar`.
name: Piton
file_extensions: [pi]
scope: source.piton

contexts:
  main:
    - include: comment
    - include: declaration
    - include: key
    - include: value

  comment:
    - match: '(?:^|(?<=\s))//.*$'
      scope: comment.line.double-slash.piton

  declaration:
    - match: '^\s*(?:({declaration})\s+)*(anchor)\s+([A-Za-z_][\w-]*)'
      captures:
        1: keyword.control.piton
        2: keyword.control.piton
        3: entity.name.type.piton
    - match: '\b({declaration})\b'
      scope: keyword.control.piton

  key:
    - match: '^\s*([\w][\w-]*)(?=\s*(?:::|:)(?:\s|$))'
      scope: entity.name.tag.piton
    - match: '(::)\s*(?:(extends)\s+)?\b({types}|[A-Za-z_][\w-]*)\b'
      captures:
        1: keyword.operator.piton
        2: keyword.control.piton
        3: support.type.piton
    - match: '^\s*(-)(?=\s)'
      scope: punctuation.definition.list.piton
    - match: '^\s*(\+\+?)(?=\s)'
      scope: keyword.operator.piton

  value:
    - match: '([^\s{{}}\[\](),"]*)(\{{)'
      captures:
        1: keyword.other.sigil.piton
        2: punctuation.section.embedded.begin.piton
      push: interpolation
    - match: '"'
      scope: punctuation.definition.string.begin.piton
      push: string
    - match: '\b\d[\d_]*(?:\.\d[\d_]*)?\b'
      scope: constant.numeric.piton
    - match: '\b({literals})\b'
      scope: constant.language.piton

  interpolation:
    - meta_scope: meta.embedded.piton
    - match: '\}}'
      scope: punctuation.section.embedded.end.piton
      pop: true
    - match: '\b({self_words})\b'
      scope: variable.language.piton
    - match: '\b({literals})\b'
      scope: constant.language.piton
    - match: '\b\d[\d_]*(?:\.\d[\d_]*)?\b'
      scope: constant.numeric.piton
    - match: '(\+\+|&&|\|\||==|!=|>=|<=|[-+*/%<>?:.])'
      scope: keyword.operator.piton
    - match: '\b[A-Za-z_][\w-]*\b'
      scope: variable.other.piton

  string:
    - meta_scope: string.quoted.double.piton
    - match: '\\.'
      scope: constant.character.escape.piton
    - match: '"'
      pop: true
"#
    )
}

fn sublime_lsp() -> String {
    r#"{
  "clients": {
    "piton": {
      "enabled": true,
      "command": ["piton", "lsp"],
      "selector": "source.piton",
      "schemes": ["file"]
    }
  }
}
"#
    .to_string()
}

fn sublime_readme() -> String {
    r#"# Piton for Sublime Text

Generated by `piton grammar`.

Copy this directory to `Packages/Piton`. Install the `LSP` package and the
bundled `LSP-piton.sublime-settings` will start `piton lsp` for `.pi` files.
"#
    .to_string()
}

// ---- Helix -------------------------------------------------------------------

fn helix_languages(source: &GrammarSource) -> String {
    format!(
        r#"# Generated by `piton grammar`. Merge into ~/.config/helix/languages.toml.

[language-server.piton]
command = "piton"
args = ["lsp"]

[[language]]
name = "piton"
scope = "source.piton"
file-types = ["pi"]
comment-token = "//"
indent = {{ tab-width = 4, unit = "    " }}
language-servers = ["piton"]
formatter = {{ command = "piton", args = ["format", "-"] }}
auto-format = true

[[grammar]]
name = "piton"
source = {{ git = "{remote}", rev = "{rev}" }}
"#,
        remote = source.repository,
        rev = source.rev
    )
}

fn helix_readme() -> String {
    r#"# Piton for Helix

Generated by `piton grammar`.

Merge `languages.toml` into `~/.config/helix/languages.toml`, then:

```sh
hx --grammar fetch
hx --grammar build
```

Point the `[[grammar]]` source at wherever you published
`editors/tree-sitter-piton`, or at a local path with
`source = { path = "/abs/path/to/editors/tree-sitter-piton" }`.
"#
    .to_string()
}

// ---- Kate ---------------------------------------------------------------------

fn kate_syntax(vocabulary: &Vocabulary) -> String {
    let item = |words: &[String]| {
        words.iter().map(|word| format!("      <item>{word}</item>")).collect::<Vec<_>>().join("\n")
    };
    format!(
        r##"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<!-- Generated by `piton grammar`. -->
<language name="Piton" version="1" kateversion="5.0" section="Configuration"
          extensions="*.pi" mimetype="text/x-piton" indenter="normal">
  <highlighting>
    <list name="keywords">
{declaration}
    </list>
    <list name="selfwords">
{self_words}
    </list>
    <list name="constants">
{literals}
    </list>
    <list name="types">
{types}
    </list>
    <contexts>
      <context name="Normal" attribute="Normal Text" lineEndContext="#stay">
        <Detect2Chars char="/" char1="/" attribute="Comment" context="Comment"/>
        <keyword String="keywords" attribute="Keyword"/>
        <keyword String="selfwords" attribute="Builtin"/>
        <keyword String="constants" attribute="Constant"/>
        <keyword String="types" attribute="Data Type"/>
        <RegExpr String="^\s*[A-Za-z_][A-Za-z0-9_-]*(?=\s*(::|:)(\s|$))" attribute="Property"/>
        <RegExpr String="[^\s{{}}\[\](),&quot;]*\{{" attribute="Sigil" context="Interpolation"/>
        <DetectChar char="&quot;" attribute="String" context="String"/>
        <RegExpr String="\b\d[\d_]*(\.\d[\d_]*)?\b" attribute="Number"/>
        <RegExpr String="^\s*-(?=\s)" attribute="Operator"/>
        <RegExpr String="^\s*\+\+?(?=\s)" attribute="Operator"/>
      </context>
      <context name="Comment" attribute="Comment" lineEndContext="#pop"/>
      <context name="String" attribute="String" lineEndContext="#pop">
        <RegExpr String="\\." attribute="Escape"/>
        <DetectChar char="&quot;" attribute="String" context="#pop"/>
      </context>
      <context name="Interpolation" attribute="Builtin" lineEndContext="#pop">
        <DetectChar char="}}" attribute="Sigil" context="#pop"/>
        <keyword String="selfwords" attribute="Builtin"/>
        <keyword String="constants" attribute="Constant"/>
        <RegExpr String="\b\d[\d_]*(\.\d[\d_]*)?\b" attribute="Number"/>
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword" defStyleNum="dsKeyword"/>
      <itemData name="Builtin" defStyleNum="dsBuiltIn"/>
      <itemData name="Constant" defStyleNum="dsConstant"/>
      <itemData name="Data Type" defStyleNum="dsDataType"/>
      <itemData name="Property" defStyleNum="dsAttribute"/>
      <itemData name="String" defStyleNum="dsString"/>
      <itemData name="Escape" defStyleNum="dsSpecialChar"/>
      <itemData name="Number" defStyleNum="dsDecVal"/>
      <itemData name="Comment" defStyleNum="dsComment"/>
      <itemData name="Operator" defStyleNum="dsOperator"/>
      <itemData name="Sigil" defStyleNum="dsPreprocessor"/>
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="//"/>
    </comments>
    <keywords casesensitive="1" additionalDeliminator="-"/>
  </general>
</language>
"##,
        declaration = item(&vocabulary.declaration),
        self_words = item(&vocabulary.self_words),
        literals = item(&vocabulary.literals),
        types = item(&vocabulary.types),
    )
}

fn kate_readme() -> String {
    r#"# Piton for Kate and KWrite

Generated by `piton grammar`.

```sh
mkdir -p ~/.local/share/org.kde.syntax-highlighting/syntax
cp piton.xml ~/.local/share/org.kde.syntax-highlighting/syntax/
```

For diagnostics and completion, enable Kate's LSP Client plugin and add:

```json
{ "servers": { "piton": { "command": ["piton", "lsp"], "highlightingModeRegex": "^Piton$" } } }
```
"#
    .to_string()
}
