//! The Tree-sitter grammar and its queries, used by Zed, Neovim, and Helix.
//!
//! The grammar is line-oriented rather than indentation-structured: Tree-sitter
//! would need an external scanner to track `INDENT`/`DEDENT`, and every editor
//! that consumes this grammar wants it for highlighting, folding, and indent
//! heuristics. Structure comes from the language server, which uses the real
//! compiler grammar.

use crate::{GeneratedFile, GrammarSource, Vocabulary};

pub fn files(vocabulary: &Vocabulary, source: &GrammarSource) -> Vec<GeneratedFile> {
    vec![
        GeneratedFile::new("tree-sitter-piton/grammar.js", grammar(vocabulary)),
        GeneratedFile::new("tree-sitter-piton/tree-sitter.json", tree_sitter_json()),
        GeneratedFile::new("tree-sitter-piton/package.json", package_json()),
        GeneratedFile::new("tree-sitter-piton/queries/highlights.scm", highlights(vocabulary)),
        GeneratedFile::new("tree-sitter-piton/queries/injections.scm", injections()),
        GeneratedFile::new("tree-sitter-piton/queries/folds.scm", folds()),
        GeneratedFile::new("tree-sitter-piton/queries/indents.scm", indents()),
        GeneratedFile::new("tree-sitter-piton/queries/outline.scm", outline()),
        GeneratedFile::new("tree-sitter-piton/queries/brackets.scm", brackets()),
        GeneratedFile::new("tree-sitter-piton/test/corpus/piton.txt", corpus()),
        GeneratedFile::new("tree-sitter-piton/test/highlight/piton.pi", highlight_test()),
        GeneratedFile::new("tree-sitter-piton/.gitignore", gitignore()),
        GeneratedFile::new("tree-sitter-piton/README.md", readme(source)),
    ]
}

fn quoted_list(words: &[String]) -> String {
    words.iter().map(|word| format!("'{word}'")).collect::<Vec<_>>().join(", ")
}

fn grammar(vocabulary: &Vocabulary) -> String {
    let literals = quoted_list(&vocabulary.literals);
    let self_words = quoted_list(&vocabulary.self_words);
    let types = quoted_list(&vocabulary.types);
    format!(
        r#"// Generated by `piton grammar`. Edit crates/piton-grammar instead.
//
// A line-oriented grammar for highlighting Piton.
//
// One design note worth knowing before editing: names, declaration keywords and
// prose all use the single `word` token. Piton lines are ambiguous until their
// end — `shape Concrete:` is a declaration and `shape concrete text` is prose —
// and giving each role its own token would force that decision on the lexer,
// which cannot see far enough. With one token the ambiguity becomes a parse
// conflict instead, which the GLR parser resolves by looking ahead.

const NAME = /[A-Za-z_][A-Za-z0-9_-]*/;

module.exports = grammar({{
  name: 'piton',

  extras: $ => [/[ \t]/],

  // Substituted into its callers so that the conflicts below can name the
  // rules a reader recognises.
  inline: $ => [$._piece],

  // A line is ambiguous until its end: `shape Concrete:` is a declaration and
  // `shape concrete text` is prose. The parser explores both and lets the
  // colon decide.
  conflicts: $ => [
    [$.keyword_declaration, $.value],
  ],

  rules: {{
    // A file is a sequence of lines. Requiring the newline matters: without it
    // two statements could sit side by side, which would make every keyword
    // valid in the middle of a sentence and turn prose into parse errors.
    //
    // Lines are grouped rather than simply repeated because of one rule: a
    // `key:` line written inside a run of prose is prose. A run ends at a blank
    // line and nowhere else, so a property is not derivable until that blank
    // line arrives — which is what stops the lexer producing a `key` token
    // there at all, since it only ever scans for tokens the parser can use.
    source_file: $ => seq(
      repeat(choice($._structural_line, $._prose_run, $._blank_line, $._comment_line)),
      // A run of prose may also end at the end of the file. Nothing may follow
      // it there either — not even the last line of the file — because a `key`
      // the parser could still use is a `key` the lexer will still produce, and
      // the longest match would take it in preference to the words it is made
      // of.
      optional(choice($._trailing_prose, $._last_line)),
    ),

    _structural_line: $ => seq($._entry, optional($.comment), $._newline),

    // A fenced code block is kept exactly as written, so nothing inside it is
    // lexed as Piton: between its fences the only tokens are whole lines.
    _code_line: $ => seq($.code_block, $._newline),

    code_block: $ => seq(
      field('open', $.fence_open),
      $._newline,
      repeat(choice(seq($.code, $._newline), $._newline)),
      field('close', $.fence_close),
    ),

    // The opening fence carries its info string, so that it is longer than
    // the word the same characters would otherwise be.
    fence_open: $ => token(prec(1, /(```+[^`\n]*|~~~+[^\n]*)/)),

    // A closing fence is nothing but the fence, so a line such as ```` ```js ````
    // inside the block is longer as `code` and stays content. Tree-sitter
    // cannot count, so any run of three or more closes the block.
    fence_close: $ => token(prec(1, /(```+|~~~+)[ \t]*/)),

    code: $ => token(prec(-2, /[^ \t\r\n][^\n]*/)),

    _blank_line: $ => $._newline,

    // Trivia: a comment never breaks a string block, so it never ends a run.
    _comment_line: $ => seq($.comment, $._newline),

    _prose_run: $ => seq($._trailing_prose, $._blank_line),

    // Right-associative: a run should always prefer taking the next line over
    // ending, which is the whole point of it.
    _trailing_prose: $ => prec.right(seq(
      // A fence is prose as far as the run is concerned: a `key:` right after
      // one is still a sentence until a blank line.
      choice($._prose_line, $._code_line),
      repeat(choice($._prose_line, $._comment_line, $._code_line)),
      // A file need not end with a newline, and the line that has none is
      // still part of the run.
      optional(seq($.text_line, optional($.comment))),
    )),

    _prose_line: $ => seq($.text_line, optional($.comment), $._newline),

    _last_line: $ => seq($._entry, optional($.comment)),

    // Everything a line may be except prose, which is grouped into runs above.
    _entry: $ => choice(
      $.import_statement,
      $.use_statement,
      $.export_statement,
      $.anchor_declaration,
      $.keyword_declaration,
      $.property,
      $.list_item,
      $.spread_item,
    ),

    _newline: $ => token(/\r?\n/),

    comment: $ => token(seq('//', /[^\n]*/)),

    // ---- imports and exports ------------------------------------------

    import_statement: $ => seq(
      'from',
      field('path', $.path),
      choice('import', 'export'),
      // `piton format` breaks long lists onto their own lines.
      choice('*', seq(optional($._newline), $.import_list)),
    ),

    // A comma continues the list, even across the line breaks `piton format`
    // introduces once a list gets long.
    import_list: $ => prec.right(seq(
      $.import_item,
      repeat(seq(',', optional($._newline), $.import_item)),
      optional(','),
    )),

    // A second word on an import item is an alias, never the next item.
    import_item: $ => prec.right(seq(field('name', $.word), optional(field('alias', $.word)))),

    use_statement: $ => seq('use', field('path', $.path)),

    export_statement: $ => seq('export', field('name', $.word)),

    path: $ => token(/[.@\/][^\s]*/),

    // ---- declarations ---------------------------------------------------

    anchor_declaration: $ => seq(
      optional('export'),
      optional('abstract'),
      'anchor',
      field('name', $.word),
      optional($.extends_clause),
      optional($.as_clause),
      ':',
    ),

    // `my-keyword Name:` — sugar for `anchor Name extends MyKeyword:`.
    keyword_declaration: $ => prec.dynamic(1, seq(
      optional('export'),
      field('keyword', $.word),
      field('name', $.word),
      optional($.extends_clause),
      optional($.as_clause),
      ':',
    )),

    extends_clause: $ => seq('extends', field('name', $.word), repeat(seq(',', field('name', $.word)))),

    as_clause: $ => seq('as', field('keyword', $.word)),

    // ---- block entries -----------------------------------------------------

    // Right-associative: a value runs to the end of its line, so the parser
    // should always prefer extending it over closing the entry.
    property: $ => prec.right(choice(
      seq(field('key', $.key), optional($.value)),
      seq(
        field('key', $.typed_key),
        $.type,
        repeat(seq('::', $.type)),
        optional(seq(':', optional($.value))),
      ),
    )),

    // The colon is part of the key token: it is the only thing that tells a
    // property apart from a line of prose, and the lexer needs to see it.
    key: $ => token(seq(NAME, /[ \t]*/, ':')),
    typed_key: $ => token(seq(NAME, /[ \t]*/, '::')),

    type: $ => prec.right(seq(
      optional('extends'),
      field('name', choice($.builtin_type, $.word)),
      repeat(seq('[', ']')),
    )),

    builtin_type: $ => choice({types}),

    // `- key: value` is a dictionary written as one element, so a list item
    // takes a property as readily as a value.
    list_item: $ => prec.right(2, seq('-', optional(choice($.property, $.value)))),

    spread_item: $ => prec.right(2, seq(choice('++', '+'), optional($.value))),

    text_line: $ => $.value,

    // ---- values ---------------------------------------------------------------

    // A line-level value: prose commas and parentheses are just text.
    value: $ => prec.right(repeat1(choice($._piece, ','))),

    // An inline-list element stops at the comma that separates it.
    element: $ => prec.right(repeat1($._piece)),

    _piece: $ => choice(
      $.url,
      $.interpolation,
      $.string,
      $.number,
      $.constant,
      $.inline_list,
      $.escape,
      $.operator,
      $.word,
      '(',
      ')',
    ),

    inline_list: $ => seq(
      '[',
      optional(seq($.element, repeat(seq(',', optional($.element))))),
      ']',
    ),

    // The sigil and its brace are one token so that `reference{{` cannot be
    // mistaken for the word `reference`. Any run of prose may be a sigil, so
    // the token is longer than the word it would otherwise lex as and wins.
    interpolation: $ => seq($.sigil, optional($.expression), '}}'),

    sigil: $ => token(seq(optional(/[^\s{{}}\[\](),"\\]+/), '{{')),

    // Inside `{{ }}` bare words are references, so identifiers replace prose.
    expression: $ => repeat1(choice(
      $.self_reference,
      $.constant,
      $.string,
      $.number,
      $.operator,
      $.identifier,
      '.',
      ',',
      '(',
      ')',
      '[',
      ']',
    )),

    identifier: $ => token(NAME),

    self_reference: $ => choice({self_words}),

    constant: $ => choice({literals}),

    string: $ => token(seq('"', repeat(choice(/\\./, /[^"\\\n]/)), '"')),

    number: $ => token(/\d[\d_]*(\.\d[\d_]*)?/),

    escape: $ => token(seq('\\', /./)),

    operator: $ => choice(
      '++', '&&', '||', '==', '!=', '>=', '<=',
      '+', '-', '*', '/', '%', '<', '>', '?', ':',
    ),

    // A URL is one token so that its `//` is never read as a comment. It is
    // longer than the `key` token that `https:` would otherwise match, and
    // longest-match settles it.
    url: $ => token(/[A-Za-z][A-Za-z0-9+.-]*:\/\/[^\s]*/),

    // Prose. `:` is excluded so that a property key always out-matches a word.
    word: $ => token(prec(-1, /[^\s{{}}\[\](),"\\:\n]+/)),
  }}
}});
"#
    )
}

/// The metadata modern Tree-sitter tooling reads to find this grammar.
///
/// Without it `tree-sitter test` cannot associate `.pi` with the parser, so the
/// highlight assertions never run.
fn tree_sitter_json() -> String {
    r#"{
  "grammars": [
    {
      "name": "piton",
      "camelcase": "Piton",
      "scope": "source.piton",
      "path": ".",
      "file-types": ["pi"],
      "highlights": ["queries/highlights.scm"],
      "injections": ["queries/injections.scm"],
      "folds": ["queries/folds.scm"],
      "indents": ["queries/indents.scm"]
    }
  ],
  "metadata": {
    "version": "0.1.0",
    "license": "MIT",
    "description": "Tree-sitter grammar for the Piton language",
    "authors": [{ "name": "Piton" }]
  },
  "bindings": {
    "c": true,
    "go": false,
    "node": true,
    "python": false,
    "rust": true,
    "swift": false
  }
}
"#
    .to_string()
}

fn package_json() -> String {
    r#"{
  "name": "tree-sitter-piton",
  "version": "0.1.0",
  "description": "Tree-sitter grammar for the Piton language",
  "main": "bindings/node",
  "keywords": ["parser", "piton"],
  "license": "MIT",
  "scripts": {
    "build": "tree-sitter generate",
    "test": "tree-sitter test"
  },
  "devDependencies": {
    "tree-sitter-cli": "^0.24.0"
  },
  "tree-sitter": [
    {
      "scope": "source.piton",
      "file-types": ["pi"],
      "highlights": "queries/highlights.scm",
      "injections": "queries/injections.scm"
    }
  ]
}
"#
    .to_string()
}

fn highlights(vocabulary: &Vocabulary) -> String {
    let framework = if vocabulary.framework.is_empty() {
        String::new()
    } else {
        format!(
            "\n; Keywords contributed by registered frameworks.\n((keyword_declaration keyword: (word) @keyword.function)\n  (#match? @keyword.function \"^({})$\"))\n",
            vocabulary.framework.join("|")
        )
    };
    format!(
        r#"; Generated by `piton grammar`.
;
; Specific patterns come first: prose is captured only inside a value, so a
; name never falls through to the catch-all.

(comment) @comment

; A fence is kept exactly as written, so its content is one string.
(fence_open) @punctuation.special
(fence_close) @punctuation.special
(code) @string

[
  "anchor"
  "abstract"
  "extends"
  "as"
  "export"
  "from"
  "import"
  "use"
] @keyword

(anchor_declaration name: (word) @type.definition)
(keyword_declaration keyword: (word) @keyword.function)
(keyword_declaration name: (word) @type.definition)
(extends_clause name: (word) @type)
(as_clause keyword: (word) @keyword.function)

(import_item name: (word) @variable)
(import_item alias: (word) @variable)
(export_statement name: (word) @variable)
(path) @string.special.path
(import_statement "*" @punctuation.special)

(key) @property
(typed_key) @property
(builtin_type) @type.builtin
(type name: (word) @type)

; The sigil token carries its own `{{`, because the lexer needs it to beat the
; word it would otherwise be. The closing brace has to be given the same scope
; explicitly, or an interpolation is bright at one end and dim at the other.
(sigil) @keyword.operator
(interpolation "}}" @keyword.operator)
(expression (identifier) @variable)
(self_reference) @variable.builtin
(constant) @constant.builtin
(number) @number
(string) @string
(url) @string.special.url
(escape) @string.escape
(operator) @operator

(list_item "-" @punctuation.special)
(spread_item ["+" "++"] @operator)

[":" "::" ","] @punctuation.delimiter
["[" "]" "(" ")"] @punctuation.bracket

; Prose, last so that nothing more specific is overwritten.
(value (word) @string)
(element (word) @string)
{framework}"#
    )
}

fn injections() -> String {
    "; Generated by `piton grammar`.\n; Piton prose is plain text; nothing is injected by default.\n"
        .to_string()
}

fn folds() -> String {
    r#"; Generated by `piton grammar`.
;
; The grammar is line-oriented, so the only structural fold it can offer is a
; wrapped import list. Block folding comes from `piton lsp`, which uses the
; compiler's own indentation-aware tree.
(import_list) @fold
(code_block) @fold
"#
    .to_string()
}

fn indents() -> String {
    r#"; Generated by `piton grammar`.
;
; A line ending in `:` opens a block; editors that prefer regex indent rules
; find the same thing in the language configuration.
((property) @indent
  (#match? @indent ":$"))

((anchor_declaration) @indent)
((keyword_declaration) @indent)
"#
    .to_string()
}

fn outline() -> String {
    r#"; Generated by `piton grammar`.
(anchor_declaration
  ["export" "abstract" "anchor"]* @context
  name: (word) @name) @item

(keyword_declaration
  keyword: (word) @context
  name: (word) @name) @item

(property key: (key) @name) @item
(property key: (typed_key) @name) @item
"#
    .to_string()
}

fn brackets() -> String {
    r#"; Generated by `piton grammar`.
("[" @open "]" @close)
("(" @open ")" @close)
(interpolation (sigil) @open "}" @close)
"#
    .to_string()
}

/// A `tree-sitter test` corpus covering the constructs that are easy to break.
fn corpus() -> String {
    r#"================
Declarations
================

export abstract anchor Shape as shape:
    description:: string

shape Concrete extends Shape:
    description: A concrete shape

---

(source_file
  (anchor_declaration name: (word) (as_clause keyword: (word)))
  (property key: (typed_key) (type name: (builtin_type)))
  (keyword_declaration
    keyword: (word)
    name: (word)
    (extends_clause name: (word)))
  (property key: (key) (value (word) (word) (word))))

================
Prose is not a declaration
================

note: see https://example.com for details, or e.g. (this) one

---

(source_file
  (property
    key: (key)
    (value (word) (url) (word) (word) (word) (word) (word) (word))))

================
Interpolation and sigils
================

message: ${name} @{Anchor} reference{Other} SeeAlso{X} !{X} {bare}

---

(source_file
  (property
    key: (key)
    (value
      (interpolation (sigil) (expression (identifier)))
      (interpolation (sigil) (expression (identifier)))
      (interpolation (sigil) (expression (identifier)))
      (interpolation (sigil) (expression (identifier)))
      (interpolation (sigil) (expression (identifier)))
      (interpolation (sigil) (expression (identifier))))))

================
Fenced code blocks
================

example:
    ```css
    .a {
      key: ${not} // not a comment

    }
    ````
    after: still prose

---

(source_file
  (property key: (key))
  (code_block
    open: (fence_open)
    (code)
    (code)
    (code)
    close: (fence_close))
  (text_line (value (word) (operator) (word) (word))))

================
Lists and spreads
================

items:
    + {super.items}
    - one

---

(source_file
  (property key: (key))
  (spread_item (value (interpolation (sigil) (expression (self_reference) (identifier)))))
  (list_item (value (word))))
"#
    .to_string()
}

/// The generated parser is committed, so nothing here may ignore `src/`.
fn gitignore() -> String {
    "# Generated by `piton grammar`.\n#\n# `src/` holds the generated parser and is committed on\n# purpose: Zed and Helix compile it, they do not run `tree-sitter generate`.\nnode_modules/\n".to_string()
}

/// A `tree-sitter test` highlight corpus.
///
/// These assertions are the difference between a grammar that parses and a
/// grammar that colours correctly, and they cover the cases where Piton is
/// unlike the languages Tree-sitter usually sees: prose is a first-class
/// value, and a keyword only means something at the head of a line.
fn highlight_test() -> String {
    r#"// A highlight corpus for `tree-sitter test`.
//
// It is a real Piton program as well as a fixture, so that opening it does not
// produce a page of errors. The one thing it cannot avoid is the warning for an
// unregistered sigil, which is the behaviour the last case is demonstrating.

use @piton/config

name: a plain sentence
// <- property

abstract anchor Skill as skill:
// <- keyword
//              ^ type.definition
//                       ^ keyword.function
    prompt:: string

anchor Example:
// <- keyword
//     ^ type.definition
    name: a plain sentence
//  ^ property
//        ^ string
    count: 42
//         ^ number
    flag: true
//        ^ constant.builtin
    quoted: "text"
//          ^ string
    computed: {self.name}
//            ^ keyword.operator
//             ^ variable.builtin
//                      ^ keyword.operator
    greeting: Hello, ${name}
//            ^ string
//                   ^ keyword.operator
    referenced: SeeAlso{name}
//              ^ keyword.operator
//                          ^ keyword.operator
    url: https://example.com/a//b
//       ^ string.special.url
    hyphen: a well-known thing
//          ^ string

skill BuildIt:
// <- keyword.function
//    ^ type.definition
    prompt: build the thing
    example:
        ```sh
        echo ${not} // an interpolation or a comment
        ```
//      ^ punctuation.special

from @piton/config import PitonConfig
// <- keyword
//   ^ string.special.path
//                        ^ variable
"#
    .to_string()
}

fn readme(source: &GrammarSource) -> String {
    format!(
        r#"# tree-sitter-piton

Generated by `piton grammar`. Build it with:

```sh
npm install
npx tree-sitter generate
npx tree-sitter test
```

The grammar is deliberately line-oriented. Piton is indentation-structured, and
tracking `INDENT`/`DEDENT` in Tree-sitter needs an external scanner; every
consumer of this grammar wants it for highlighting, folding, and indent
heuristics, all of which work per line. Structural questions — resolution,
inheritance, diagnostics — are answered by `piton lsp`, which uses the real
compiler grammar.

## Where this comes from

This directory is generated from the Piton compiler and published as its own
repository, because Zed, Helix, and nvim-treesitter all fetch grammars over git
rather than from a directory:

    {remote}

The Piton repository is the source of truth; run `cargo xtask publish-grammar`
there rather than committing here.

`src/` holds the output of `tree-sitter generate` and is committed on purpose:
the editors that consume this grammar compile `src/parser.c`, they do not run
the Tree-sitter CLI.
"#,
        remote = source.repository
    )
}
