;;; piton-mode.el --- Major mode for the Piton language -*- lexical-binding: t; -*-

;; Generated by `piton grammar'.  Edit crates/piton-grammar instead.

;; Version: 0.1.0
;; Package-Requires: ((emacs "27.1"))
;; Keywords: languages

;;; Commentary:

;; Font locking, indentation, and language-server registration for Piton
;; (`.pi') files.  Piton is whitespace-structured, so indentation is handled by
;; cycling through plausible levels rather than by guessing one.

;;; Code:

(defgroup piton nil
  "Support for the Piton language."
  :group 'languages
  :prefix "piton-")

(defcustom piton-indent-offset 4
  "Number of spaces per indentation level.  Piton's canonical style is four."
  :type 'integer
  :group 'piton)

(defcustom piton-command "piton"
  "Path to the piton executable."
  :type 'string
  :group 'piton)

(defconst piton--keywords '("anchor" "abstract" "extends" "as" "export" "from" "import" "use"))
(defconst piton--self-words '("this" "self" "super"))
(defconst piton--constants '("true" "false" "null"))
(defconst piton--types '("string" "number" "boolean" "null" "list" "dictionary" "anchor" "any" "simple" "complex"))
(defconst piton--framework-keywords '("agent" "belay-adapter" "belay-agent-adapter" "belay-config" "command" "instruction" "skill"))

(defconst piton-font-lock-keywords
  (list
   ;; A comment starts a line or follows whitespace, so URLs survive.
   '("\\(?:^\\|[[:space:]]\\)\\(//.*\\)$" 1 font-lock-comment-face)
   `(,(concat "\\_<" (regexp-opt piton--keywords) "\\_>") . font-lock-keyword-face)
   `(,(concat "\\_<" (regexp-opt piton--self-words) "\\_>") . font-lock-builtin-face)
   `(,(concat "\\_<" (regexp-opt piton--constants) "\\_>") . font-lock-constant-face)
   (when piton--framework-keywords
     `(,(concat "^[[:space:]]*" (regexp-opt piton--framework-keywords) "\\_>")
       . font-lock-preprocessor-face))
   '("^[[:space:]]*\\(?:export[[:space:]]+\\)?\\(?:abstract[[:space:]]+\\)?anchor[[:space:]]+\\([A-Za-z_][A-Za-z0-9_-]*\\)"
     1 font-lock-type-face)
   '("^[[:space:]]*\\([A-Za-z_][A-Za-z0-9_-]*\\)[[:space:]]*\\(?:::\\|:\\)\\(?:[[:space:]]\\|$\\)"
     1 font-lock-variable-name-face)
   `(,(concat "::[[:space:]]*\\(?:extends[[:space:]]+\\)?\\("
              (regexp-opt piton--types) "\\|[A-Za-z_][A-Za-z0-9_-]*\\)")
     1 font-lock-type-face)
   '("[^ \t{}\\[\\](),\"]*{[^}]*}" 0 font-lock-preprocessor-face keep)
   '("\\_<[0-9][0-9_]*\\(?:\\.[0-9][0-9_]*\\)?\\_>" . font-lock-constant-face)
   '("^[[:space:]]*\\(-\\)[[:space:]]" 1 font-lock-negation-char-face)
   '("^[[:space:]]*\\(\\+\\+?\\)[[:space:]]" 1 font-lock-warning-face))
  "Font lock rules for `piton-mode'.")

(defvar piton-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?/ ". 12" table)
    (modify-syntax-entry ?\n ">" table)
    (modify-syntax-entry ?\" "\"" table)
    (modify-syntax-entry ?- "_" table)
    (modify-syntax-entry ?_ "_" table)
    table)
  "Syntax table for `piton-mode'.")

(defun piton--previous-indent ()
  "Indentation of the closest preceding non-blank line."
  (save-excursion
    (forward-line -1)
    (while (and (not (bobp)) (looking-at "^[[:space:]]*$"))
      (forward-line -1))
    (cons (current-indentation)
          (save-excursion (end-of-line) (looking-back ":[[:space:]]*" (line-beginning-position))))))

(defun piton-indent-line ()
  "Indent the current line, cycling through plausible levels on repeat."
  (interactive)
  (let* ((previous (piton--previous-indent))
         (base (car previous))
         (opens (cdr previous))
         (maximum (+ base (if opens piton-indent-offset 0)))
         (current (current-indentation)))
    (indent-line-to
     (if (and (eq last-command 'indent-for-tab-command) (> current 0))
         (max 0 (- current piton-indent-offset))
       maximum))))

(defun piton-format-buffer ()
  "Format the current buffer with `piton format'."
  (interactive)
  (let ((point (point)))
    (call-process-region (point-min) (point-max) piton-command t t nil "format" "-")
    (goto-char (min point (point-max)))))

;;;###autoload
(define-derived-mode piton-mode prog-mode "Piton"
  "Major mode for editing Piton source."
  :syntax-table piton-mode-syntax-table
  (setq-local font-lock-defaults '(piton-font-lock-keywords nil nil nil nil))
  (setq-local comment-start "// ")
  (setq-local comment-end "")
  (setq-local comment-start-skip "//+[[:space:]]*")
  (setq-local indent-line-function #'piton-indent-line)
  (setq-local indent-tabs-mode nil)
  (setq-local tab-width piton-indent-offset)
  (setq-local require-final-newline t))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.pi\\'" . piton-mode))

;; Language server registration for both popular clients.
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               `(piton-mode . (,piton-command "lsp"))))

(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration '(piton-mode . "piton"))
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection (list piton-command "lsp"))
                    :activation-fn (lsp-activate-on "piton")
                    :server-id 'piton)))

(provide 'piton-mode)
;;; piton-mode.el ends here
