// Generated by `piton grammar`.
package dev.piton

import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.platform.lsp.api.LspServerSupportProvider
import com.intellij.platform.lsp.api.ProjectWideLspServerDescriptor

/** Starts `piton lsp` for every `.pi` file in the project. */
class PitonLspServerSupportProvider : LspServerSupportProvider {
    override fun fileOpened(
        project: Project,
        file: VirtualFile,
        serverStarter: LspServerSupportProvider.LspServerStarter,
    ) {
        if (file.extension == "pi") {
            serverStarter.ensureServerStarted(PitonLspServerDescriptor(project))
        }
    }
}

private class PitonLspServerDescriptor(project: Project) :
    ProjectWideLspServerDescriptor(project, "Piton") {

    override fun isSupportedFile(file: VirtualFile) = file.extension == "pi"

    override fun createCommandLine() =
        com.intellij.execution.configurations.GeneralCommandLine("piton", "lsp")
}
