-- Generated by `piton grammar`.
--
-- Registers Piton with Neovim's built-in LSP client and, when the Tree-sitter
-- grammar is installed, with nvim-treesitter.

local M = {}

--- @param opts table|nil  Passed through to vim.lsp.start.
function M.setup(opts)
  opts = opts or {}
  vim.filetype.add({ extension = { pi = 'piton' } })

  local group = vim.api.nvim_create_augroup('PitonLsp', { clear = true })
  vim.api.nvim_create_autocmd('FileType', {
    group = group,
    pattern = 'piton',
    callback = function(args)
      vim.lsp.start(vim.tbl_extend('force', {
        name = 'piton',
        cmd = opts.cmd or { 'piton', 'lsp' },
        root_dir = vim.fs.dirname(vim.fs.find({ 'piton.config.pi', '.git' }, {
          upward = true,
          path = vim.api.nvim_buf_get_name(args.buf),
        })[1]),
      }, opts))
    end,
  })

  local ok, parsers = pcall(require, 'nvim-treesitter.parsers')
  if ok then
    parsers.get_parser_configs().piton = {
      install_info = {
        url = opts.grammar_url or 'ssh://dev.mdynx.net/piton/tree-sitter-piton.git',
        revision = opts.grammar_revision or '3aa648becacded0061c316030d3a01a4b45284c3',
        files = { 'src/parser.c' },
      },
      filetype = 'piton',
    }
  end
end

return M
