" Generated by `piton grammar`.
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

setlocal expandtab
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal tabstop=4
setlocal commentstring=//\ %s
setlocal comments=:https://,:// 
setlocal foldmethod=indent
setlocal formatprg=piton\ format\ -
