// Generated by `piton grammar`.
//
// A thin client: everything interesting happens in `piton lsp`.

const { workspace, window, commands } = require('vscode');
const { LanguageClient, TransportKind } = require('vscode-languageclient/node');

let client;

function serverOptions() {
  const command = workspace.getConfiguration('piton').get('serverPath', 'piton');
  const run = { command, args: ['lsp'], transport: TransportKind.stdio };
  return { run, debug: run };
}

function start() {
  client = new LanguageClient('piton', 'Piton Language Server', serverOptions(), {
    documentSelector: [{ scheme: 'file', language: 'piton' }],
    synchronize: {
      fileEvents: workspace.createFileSystemWatcher('**/*.pi'),
    },
  });
  return client.start();
}

async function activate(context) {
  context.subscriptions.push(
    commands.registerCommand('piton.restartServer', async () => {
      if (client) await client.stop();
      await start();
      window.showInformationMessage('Piton language server restarted.');
    }),
    commands.registerCommand('piton.build', async () => {
      const terminal = window.createTerminal('piton build');
      terminal.sendText('piton build');
      terminal.show();
    }),
  );
  await start();
}

async function deactivate() {
  if (client) await client.stop();
}

module.exports = { activate, deactivate };
